spring:
  application:
    name: AuthenticationService

  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: ${PORT:8081}